# Este Dockerfile atualiza a imagem oficial do Nginx para a versão estável baseada em Alpine Linux.
FROM nginx:stable-alpine 

# Copia o arquivo de configuração personalizado para o diretório de configuração do Nginx
COPY default.conf /etc/nginx/conf.d/default.conf